### ISSUE TITLE
Set-up a translation infrastructure

### ISSUE THREAD

**Issue by ruphy** [publiccodeyml/publiccode.yml#75]
We need a simple way to manage translations and evolve the standard with automated consistency checks.

The master copy needs to be developed in English, translations are handled with a separate workflow and can be done separately. With a build-like process translated versions are created and uploaded, without the need for manual merges.

**Comment by ruphy** [comment]
@bfabio and I decided to try out the following approach:

- [ ] use Gettext as underlying backend for translators
- [ ] implement a custom .pot/.po utility for parsing our dialect of rst correctly (e.g. understanding the "Key: `key`" syntax)
- [ ] implement two scripts to: `generate_pot_merge_po` (to create pot files and merge them into existing po files); `generate_doc` (to generate doc from the master english copy and the translated po files)
- [ ] (later) integrate this system with a CI toolchain

**Comment by bfabio** [comment]
Update: after further discussion, we agreed that a solution based on the built-in i18n mechanism in Sphinx would be more beneficial, resulting in a semplification and a better alignment with upstream practices.

**Comment by bfabio** [comment]
We kept it simple, see #77.
